version: '2.4'
services:
  ica:
    image: xtrime/ica:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: 'no'
    volumes:
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "9003"
      - "127.0.0.1:3000:3000"
    entrypoint: "php artisan serve --host 0.0.0.0"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"