version: '2.4'
x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '1m'
    max-file: '2'

services:
  ica:
    image: xtrime/ica:latest
    container_name: ica
    build:
      context: ./
      dockerfile: Dockerfile
    restart: 'no'
    volumes:
      - ./:/ica
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    working_dir: /ica
    command:
      - "composer install -o --no-dev && composer dump-auto --apcu && php artisan optimize && php artisan serve --host 0.0.0.0"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mysql
    logging: *default-logging
  mysql:
    image: mariadb:10.9
    container_name: ica-mysql
    restart: always
    ports:
      - "127.0.0.1:9407:3306"
    volumes:
      - ./.mysql:/var/lib/mysql:delegated
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_AUTO_UPGRADE: 'yes'
    command:
      - --skip-grant-tables
      - --innodb-buffer-pool-size=32M
      - --wait_timeout=65
    logging: *default-logging
  npm:
    image: node:20-alpine
    container_name: ica-npm
    volumes:
      - ./:/ica
    working_dir: /ica
    command: "npm run production"
    logging: *default-logging
networks:
  default:
    external: false
    name: ica-network
